Repository hacf-fr/awesome-francophone-home-assistant, pull requests merged in 2020-11, with the labels that each got.

#25 Create CODEOWNERS
  CODEOWNERS
Labels: enhancement

#36 Déplacement des contenus obsolètes dans les archives
  archives.md
  readme.md
Labels: cleaning

#37 Use Mkdocs to generate a static site
  .gitignore
  CODEOWNERS
  CONTRIBUTING.md
  README.md
  docs/requirements.txt
  mkdocs.yml
  noxfile.py
Labels: ci, enhancement

#45 Vérifie la génération et déploiement de la version HTML statique du site en CI
  .github/dependabot.yml
  .github/workflows/constraints.txt
  .github/workflows/docs.yml
  .github/workflows/docs_deploy.yml
  noxfile.py
Labels: ci

#46 Force push when deploying static site
  .github/workflows/docs.yml
  .github/workflows/docs_deploy.yml
  noxfile.py
Labels: bug, ci

#48 Fix static site building.
  docs/requirements.txt
  mkdocs.yml
Labels: bug

#41 Application du formatage Markdown pour la description de la Licence
  license
Labels: documentation

#40 ajout du lien vers Github Flavored Markdown
  CONTRIBUTING.md
Labels: bug, documentation

#42 Amélioration du guide du contributeur
  CONTRIBUTING.md
Labels: documentation
