Repository hacf-fr/awesome-francophone-home-assistant, pull requests merged in 2020-10, with the labels that each got.

#8 Fix linting errors
  readme.md
Labels: Style

#6 Add Oncleben31 Home Assistant configuration
  readme.md
Labels: New link

#11 Lien vers la chaine YouTube du Journal de Thomas
  readme.md
Labels: Hacktoberfest, New link

#12 Ajout du lien vers le blog My Canaletto
  readme.md
Labels: Hacktoberfest, New link

#13 Ajout du lien vers le blog A quoi ça sert
  readme.md
Labels: Hacktoberfest, New link

#14 Ajout du lien vers le blog Tech Café
  readme.md
Labels: Hacktoberfest, New link

#15 Improve CI
  .github/dependabot.yml
  .github/workflows/awesome.yml
  .github/workflows/push_pull.yml
Labels: Hacktoberfest, enhancement
